version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: siec
            MYSQL_USER: siec
            MYSQL_PASSWORD: siec
        volumes:
            - ./mysql:/var/lib/mysql:cached
        networks:
            - db
        ports:
            - "3306:3306"
    adminer:
        container_name: adminer
        image: adminer
        restart: on-failure
        networks:
            - db
        ports:
          - "8080:8080"
        depends_on: 
            - db
    php:
        container_name: php-fpm
        build: ./php-fpm
        restart: on-failure
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/log:cached
        networks:
            - db
            - php
        ports:
            - "9000:9001"
        depends_on: 
            - db
    nginx:
        container_name: nginx
        build: ./nginx
        restart: on-failure
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/symfony:cached
        networks:
            - php
        ports:
            - "80:80"
        depends_on: 
            - php
networks:
    db:
    php:
